plugins {
    id 'groovy'
}

group = 'pl.olafcio'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.apache.groovy:groovy:6.0.0'
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    compileOnly gradleApi()
}

test {
    useJUnitPlatform()
}

base {
    archivesName = "github.gradle.plugin"
}
